
export const GameAssets = {
    IMG_PREFIX: './images/',
    MODEL_ASSET_PATH_PREFIX: './models/',
    MODEL_DATA_PATH_PREFIX: './models/',
    
    // --- Textures ---
    // Texture vocabulary is generated from file-based pack entries and alias fallbacks.
    textureManifest: {},
    textureAliasManifest: {
        'PIPES_1A.png': 'suprt3.png',
        'TECH_2F.png': 'wall_panel_damaged.png',
        'CRATE_1D.png': 'door_security_heavy.png',
        'terminal_screen_off.png': { color: 0x111418 },
        'GRID_1A.png': 'darktiles.png',
        'horror_concrete_color.png': 'concretewall.png',
        'STEEL_1A.png': 'darktiles.png',
        'lite1.png': 'LIGHT_1B.png',
        'WARN_1A.png': { color: 0xb34141 },
        'iron.png': 'darktiles.png',
        'level-2-keycard.png': 'level1keycard.png',
        'level-3-keycard.png': 'level1keycard.png',
        'real_cobblestone.png': 'concretewall.png',
        'cable_straight_detail.png': { color: 0x59616a },
        'cable_curved_detail.png': { color: 0x59616a },
        'cable_split_detail.png': { color: 0x59616a },
        'caution_stripes_refined.png': { color: 0xcf9a24 },
        'blood_drag_detail.png': { color: 0x5f1116 },
        'blood_drip_detail.png': { color: 0x691117 },
        'blood_splatter_detail.png': { color: 0x5b0b12 },
        'blood_splotch_detail.png': { color: 0x651018 },

        'city_asphalt_01.jpg': 'darktiles.png',
        'city_parking_lot.png': 'darktiles.png',
        'city_roadmarkings.png': 'LIGHT_1B.png',
        'city_roadrail.jpg': 'door_security_heavy.png',
        'city_concrete_01.jpg': 'concretewall.png',
        'city_bricks_18.png': 'concretewall.png',
        'city_bricks_08.png': 'concretewall.png',
        'city_bricks_24.png': 'concretewall.png',
        'city_bricks_05.png': 'concretewall.png',
        'city_plaster_07.png': 'concretewall.png',
        'city_tile_12.png': 'darktiles.png',
        'city_tile_21.png': 'darktiles.png',
        'city_wood_18.png': 'door_security_heavy.png',
        'city_metal_03.png': 'wall_panel_damaged.png',
        'city_metal_11.png': 'suprt3.png',
        'city_metal_16.png': 'wall_panel_damaged.png',
        'city_metal_21.png': 'darktiles.png',
        'city_grating_06.png': 'darktiles.png',
        'city_grating_14.png': 'darktiles.png',
        'city_elements_08.png': 'wall_panel_damaged.png',
        'city_lights.jpg': 'LIGHT_1B.png',
        'city_lights_emissive.png': 'LIGHT_1B.png',
        'city_lights_01.jpg': 'LIGHT_1B.png',
        'city_sign.jpg': { color: 0xc9882b },
        'city_sign_01.png': { color: 0xc9882b },
        'city_outdoor_electronics.jpg': 'wall_panel_damaged.png',
        'city_control.jpg': 'wall_panel_damaged.png',
        'city_office.jpg': 'door_security_heavy.png',
        'city_door_03.jpg': 'door_security_heavy.png',
        'city_door_01.jpg': 'door_security_heavy.png',
        'city_door_02.jpg': 'door_security_heavy.png',
        'city_roof_tiles.jpg': 'darktiles.png',
        'city_tiles.jpg': 'darktiles.png',
        'city_plastic_02.png': 'wall_panel_damaged.png',
        'city_plastic_07.png': 'wall_panel_damaged.png',
        'city_store_fridge.png': 'LIGHT_1B.png',
        'city_fridge_01.jpg': 'LIGHT_1B.png',
        'city_fridge_emissive.png': 'LIGHT_1B.png',
        'city_plants_01.png': { color: 0x4f8c4d },
        'city_plants_02.png': { color: 0x4f8c4d },

        'Prototype_black_32x32px_02.png': { color: 0x14171b },
        'Prototype_blue_32x32px_02.png': { color: 0x3f6fbf },
        'Prototype_blue_persian_32x32px_02.png': { color: 0x4c65a6 },
        'Prototype_checkers_01_32x32px_02.png': { color: 0x72767c },
        'Prototype_checkers_02_32x32px_02.png': { color: 0x80848a },
        'Prototype_checkers_03_32x32px_02.png': { color: 0x6d7277 },
        'Prototype_checkers_04_32x32px_02.png': { color: 0x787d82 },
        'Prototype_cyan_32x32px_02.png': { color: 0x4daab6 },
        'Prototype_cyan_fountain_32x32px_02.png': { color: 0x4d9fa8 },
        'Prototype_green_32x32px_02.png': { color: 0x4b8b52 },
        'Prototype_green_lime_32x32px_02.png': { color: 0x74b14a },
        'Prototype_grey_32x32px_02.png': { color: 0x7a7a7a },
        'Prototype_grey_dark_32x32px_02.png': { color: 0x4c4f55 },
        'Prototype_orange_32x32px_02.png': { color: 0xbe7d31 },
        'Prototype_orange_ochre_32x32px_02.png': { color: 0xb27c3f },
        'Prototype_pink_32x32px_02.png': { color: 0xc07aa6 },
        'Prototype_purple_32x32px_02.png': { color: 0x8455a5 },
        'Prototype_red_32x32px_02.png': { color: 0xa84848 },
        'Prototype_red_carmine_32x32px_02.png': { color: 0x8f2f3d },
        'Prototype_symbol_cross_32x32px_02.png': { color: 0xb9b9b9 },
        'Prototype_symbol_no_32x32px_02.png': { color: 0xa84848 },
        'Prototype_symbol_skull_32x32px_02.png': { color: 0xc7c7c7 },
        'Prototype_texture_atlas_32x32px_02.png': { color: 0x6f7478 },
        'Prototype_transparent_32x32px_02.png': { color: 0x5d636a },
        'Prototype_trigger_32x32px_02.png': { color: 0xb89d37 },
        'Prototype_water_32x32px_02.png': { color: 0x3f78a6 },
        'Prototype_white_32x32px_02.png': { color: 0xd3d7db },
        'Prototype_yellow_32x32px_02.png': { color: 0xc6b048 },
        'Prototype_yellow_gold_32x32px_02.png': { color: 0xb89d37 }
    },

    // --- Models ---
    // Add JSON under ./models/<name>.json or register GLB/FBX here when Raw Iron ships packaged art.
    availableModels: [],
    animationLibraryProfiles: {},
    externalModels: {}
};
