if (NOT DEFINED RAWIRON_WORKSPACE)
  message(FATAL_ERROR "RAWIRON_WORKSPACE must point at the RawIron workspace root.")
endif()

set(rendering_script "${RAWIRON_WORKSPACE}/Games/LiminalHall/scripts/rendering.riscript")
if (NOT EXISTS "${rendering_script}")
  message(FATAL_ERROR "Expected Liminal Hall rendering script at ${rendering_script}")
endif()

file(READ "${rendering_script}" rendering_text)
if (NOT rendering_text MATCHES "clear_top_r=")
  message(FATAL_ERROR "rendering.riscript is missing clear_top_r atmosphere key.")
endif()
if (NOT rendering_text MATCHES "fog_r=")
  message(FATAL_ERROR "rendering.riscript is missing fog_r atmosphere key.")
endif()
if (NOT rendering_text MATCHES "fog_far_r=")
  message(FATAL_ERROR "rendering.riscript is missing fog_far_r atmosphere key.")
endif()

set(postprocess_script "${RAWIRON_WORKSPACE}/Games/LiminalHall/scripts/postprocess.riscript")
if (NOT EXISTS "${postprocess_script}")
  message(FATAL_ERROR "Expected Liminal Hall postprocess script at ${postprocess_script}")
endif()
file(READ "${postprocess_script}" postprocess_text)
if (NOT postprocess_text MATCHES "native_exposure")
  message(FATAL_ERROR "postprocess.riscript is missing native_exposure key.")
endif()
if (NOT postprocess_text MATCHES "bloom_strength")
  message(FATAL_ERROR "postprocess.riscript is missing bloom_strength key.")
endif()
if (NOT postprocess_text MATCHES "sharpen_amount")
  message(FATAL_ERROR "postprocess.riscript is missing sharpen_amount key.")
endif()

message(STATUS "VerifyRenderingScriptPreview: Liminal Hall rendering/postprocess scripts contain preview keys.")
