if(NOT DEFINED RAWIRON_WORKSPACE)
  message(FATAL_ERROR "RAWIRON_WORKSPACE is required")
endif()

set(_shaders "${RAWIRON_WORKSPACE}/Source/RawIron.Render.Vulkan/shaders")
set(_cmake "${RAWIRON_WORKSPACE}/Source/RawIron.Render.Vulkan/CMakeLists.txt")
set(_required
  "${_shaders}/SerenityColorCommon.glsl"
  "${_shaders}/SerenityColorTransforms.glsl"
  "${_shaders}/SerenityColorDither.glsl"
  "${_shaders}/SerenityRadiance.glsl"
  "${_shaders}/SerenityTemporal.glsl"
  "${_shaders}/SerenityCloudNoise.glsl"
  "${_shaders}/SerenityExposure.glsl"
  "${_shaders}/SerenityExposure.frag"
  "${_shaders}/SerenityToneMap.vert"
  "${_shaders}/SerenityToneMap.frag"
  "${_shaders}/SerenityComposite.frag"
)
foreach(_path IN LISTS _required)
  if(NOT EXISTS "${_path}")
    message(FATAL_ERROR "Native Serenity color shader missing: ${_path}")
  endif()
  file(READ "${_path}" _text)
  if(_text MATCHES "#include[^\n]*Bliss" OR _text MATCHES "#include[^\n]*ThirdParty")
    message(FATAL_ERROR "Serenity shader still includes ThirdParty/Bliss: ${_path}")
  endif()
endforeach()

file(READ "${_cmake}" _cmake_text)
string(FIND "${_cmake_text}" "-I\${PROJECT_SOURCE_DIR}/ThirdParty" _include)
if(NOT _include EQUAL -1)
  message(FATAL_ERROR "Vulkan shader compile still searches ThirdParty")
endif()
string(FIND "${_cmake_text}" "ThirdParty/Bliss" _dep)
if(NOT _dep EQUAL -1)
  message(FATAL_ERROR "Vulkan shader compile still depends on ThirdParty/Bliss")
endif()

file(READ "${_shaders}/SerenityColorCommon.glsl" _common)
foreach(_needle IN ITEMS "SerenityColorTransforms.glsl" "SerenityColorDither.glsl" "SerenityToneMap" "int8Dither")
  string(FIND "${_common}" "${_needle}" _found)
  if(_found EQUAL -1)
    message(FATAL_ERROR "SerenityColorCommon is missing ${_needle}")
  endif()
endforeach()

file(READ "${_shaders}/SerenityToneMap.frag" _tone)
foreach(_needle IN ITEMS "SerenityRadiance.glsl" "SerenityPrepareRadiance" "vExposure")
  string(FIND "${_tone}" "${_needle}" _found)
  if(_found EQUAL -1)
    message(FATAL_ERROR "SerenityToneMap is missing ${_needle}")
  endif()
endforeach()
file(READ "${_shaders}/SerenityToneMap.vert" _tone_vert)
foreach(_needle IN ITEMS "SerenityExposure.glsl" "texelFetch" "serenityExposureHistory")
  string(FIND "${_tone_vert}" "${_needle}" _found)
  if(_found EQUAL -1)
    message(FATAL_ERROR "SerenityToneMap.vert is missing ${_needle}")
  endif()
endforeach()
file(READ "${_shaders}/SerenityRadiance.glsl" _radiance)
foreach(_needle IN ITEMS "SerenityVolumetricLight" "SerenityExposure.glsl" "SerenityWorldFromDepth" "textureLod" "SerenityPrepareRadiance")
  string(FIND "${_radiance}" "${_needle}" _found)
  if(_found EQUAL -1)
    message(FATAL_ERROR "SerenityRadiance is missing ${_needle}")
  endif()
endforeach()
file(READ "${_shaders}/SerenityExposure.glsl" _exposure)
foreach(_needle IN ITEMS "SerenityR2" "textureLod" "serenityExposureHistory")
  string(FIND "${_exposure}" "${_needle}" _found)
  if(_found EQUAL -1)
    message(FATAL_ERROR "SerenityExposure is missing ${_needle}")
  endif()
endforeach()
file(READ "${_shaders}/NativeSkybox.frag" _sky)
string(FIND "${_sky}" "SerenityCloudNoise.glsl" _cloud)
if(_cloud EQUAL -1)
  message(FATAL_ERROR "NativeSkybox is missing shared Serenity cloud noise")
endif()
file(READ "${_shaders}/SerenityTemporal.glsl" _temporal_src)
foreach(_needle IN ITEMS "SerenityClosestToCamera" "SerenityFastCatmulRom" "velocity" "SerenityTaaTonemap")
  string(FIND "${_temporal_src}" "${_needle}" _found)
  if(_found EQUAL -1)
    message(FATAL_ERROR "SerenityTemporal is missing ${_needle}")
  endif()
endforeach()
file(READ "${_shaders}/SerenityComposite.frag" _composite)
string(FIND "${_composite}" "SerenityTemporal" _temporal)
if(_temporal EQUAL -1)
  message(FATAL_ERROR "SerenityComposite is missing native TAA")
endif()

if(DEFINED RAWIRON_BINARY_SHADER_DIR)
  foreach(_spv IN ITEMS SerenityExposure.frag.spv SerenityToneMap.vert.spv SerenityToneMap.frag.spv SerenityComposite.frag.spv)
    if(NOT EXISTS "${RAWIRON_BINARY_SHADER_DIR}/${_spv}")
      message(FATAL_ERROR "Serenity SPIR-V was not compiled: ${_spv}")
    endif()
  endforeach()
endif()

message(STATUS "Verified native Serenity color stage does not compile ThirdParty/Bliss")
