if(NOT DEFINED RAWIRON_WORKSPACE)
  message(FATAL_ERROR "RAWIRON_WORKSPACE is required")
endif()

set(_reference "${RAWIRON_WORKSPACE}/Source/RawIron.Render.Vulkan/ReferenceShaders/Shaders/CropResize/Resizer.fx")
set(_native_asset "${RAWIRON_WORKSPACE}/Source/RawIron.Render.Vulkan/shaders/NativeEffects/crop_resize.rishader")
set(_full_shader "${RAWIRON_WORKSPACE}/Source/RawIron.Render.Vulkan/shaders/NativeComposite.frag")
set(_fast_shader "${RAWIRON_WORKSPACE}/Source/RawIron.Render.Vulkan/shaders/NativeHybridComposite.frag")
set(_runtime "${RAWIRON_WORKSPACE}/Source/RawIron.Render.Vulkan/src/VulkanNativeScenePreview.cpp")
set(_notices "${RAWIRON_WORKSPACE}/Source/RawIron.Render.Vulkan/shaders/THIRD_PARTY_NOTICES.md")
set(_native_texture_dir "${RAWIRON_WORKSPACE}/Source/RawIron.Render.Vulkan/shaders/NativeTextures")
set(_barbatos_reference "${RAWIRON_WORKSPACE}/Source/RawIron.Render.Vulkan/ReferenceShaders/Shaders/Barbatos/uFakeHDR.fx")
set(_barbatos_texture_reference "${RAWIRON_WORKSPACE}/Source/RawIron.Render.Vulkan/ReferenceShaders/Textures/Barbatos/Barbatos/Barbatos_LUT_Atlas.png")
set(_barbatos_asset "${RAWIRON_WORKSPACE}/Source/RawIron.Render.Vulkan/shaders/NativeEffects/barbatos_fake_hdr.rishader")
set(_barbatos_texture "${RAWIRON_WORKSPACE}/Source/RawIron.Render.Vulkan/shaders/NativeTextures/Barbatos/Barbatos_LUT_Atlas.png")
set(_owned_effect_sources BaBa_Deband.fx JaSharpen.fx S_Outline.fx)
set(_owned_effect_assets
  ri_adaptive_deband.rishader
  ri_local_sharpen.rishader
  ri_ink_outline.rishader
  ri_signal_glitch.rishader
  ri_night_vision.rishader
  ri_high_pass_sharpen.rishader
  ri_blending.rishader
  ri_text_overlay.rishader
  ri_shader_macros.rishader
  ri_shader_contract.rishader
  ri_shader_ui_contract.rishader
  ri_hq4x.rishader
  ri_hsl_shift.rishader
  ri_levels_plus.rishader
  ri_light_dof.rishader
  ri_magic_bloom.rishader
  ri_ui_mask.rishader)
set(_retired_root_effects
  Glitch.fx NightVision.fx HighPassSharpen.fx
  Blending.fxh DrawText.fxh HQ4X.fx HSLShift.fx LevelsPlus.fx LightDoF.fx
  Macros.fxh MagicBloom.fx ReShade.fxh ReShadeUI.fxh UIMask.fx)
set(_pd80_native_asset "${RAWIRON_WORKSPACE}/Source/RawIron.Render.Vulkan/shaders/NativeEffects/pd80_cinetools_lut.rishader")
set(_retired_pd80_helpers PD80_LUT_v2.fxh PD80_00_Noise_Samplers.fxh PD80_00_Color_Spaces.fxh)

if(EXISTS "${_reference}")
  message(FATAL_ERROR "Verified CropResize reference source should be removed after native migration")
endif()
foreach(_required IN ITEMS "${_native_asset}" "${_full_shader}" "${_fast_shader}" "${_notices}")
  if(NOT EXISTS "${_required}")
    message(FATAL_ERROR "Native shader migration artifact missing: ${_required}")
  endif()
endforeach()

foreach(_source IN LISTS _owned_effect_sources)
  if(EXISTS "${RAWIRON_WORKSPACE}/Source/RawIron.Render.Vulkan/ReferenceShaders/Shaders/Barbatos/${_source}")
    message(FATAL_ERROR "Retired capability-checklist source still exists: ${_source}")
  endif()
endforeach()
foreach(_source IN LISTS _retired_root_effects)
  if(EXISTS "${RAWIRON_WORKSPACE}/Source/RawIron.Render.Vulkan/ReferenceShaders/Shaders/${_source}")
    message(FATAL_ERROR "Retired root capability-checklist source still exists: ${_source}")
  endif()
endforeach()
foreach(_asset IN LISTS _owned_effect_assets)
  if(NOT EXISTS "${RAWIRON_WORKSPACE}/Source/RawIron.Render.Vulkan/shaders/NativeEffects/${_asset}")
    message(FATAL_ERROR "Raw Iron-owned post capability asset missing: ${_asset}")
  endif()
endforeach()
foreach(_helper IN LISTS _retired_pd80_helpers)
  if(EXISTS "${RAWIRON_WORKSPACE}/Source/RawIron.Render.Vulkan/ReferenceShaders/Shaders/PD80/${_helper}")
    message(FATAL_ERROR "PD80 native LUT helper still exists after verified migration: ${_helper}")
  endif()
endforeach()
if(NOT EXISTS "${_pd80_native_asset}")
  message(FATAL_ERROR "PD80 native Cinetools LUT asset is missing")
endif()

if(EXISTS "${_barbatos_reference}" OR EXISTS "${_barbatos_texture_reference}")
  message(FATAL_ERROR "Verified Barbatos uFakeHDR reference files should be removed after native migration")
endif()
foreach(_required IN ITEMS "${_barbatos_asset}" "${_barbatos_texture}")
  if(NOT EXISTS "${_required}")
    message(FATAL_ERROR "Native Barbatos migration artifact missing: ${_required}")
  endif()
endforeach()
if(DEFINED RAWIRON_BINARY_SHADER_DIR AND NOT EXISTS "${RAWIRON_BINARY_SHADER_DIR}/NativeTextures/Barbatos/Barbatos_LUT_Atlas.png")
  message(FATAL_ERROR "Native Barbatos LUT atlas was not staged with SPIR-V")
endif()

if(EXISTS "${RAWIRON_WORKSPACE}/Source/RawIron.Render.Vulkan/ReferenceShaders/Textures")
  message(FATAL_ERROR "ReferenceShaders/Textures must not exist after complete native texture migration")
endif()
file(GLOB_RECURSE _all_native_textures LIST_DIRECTORIES false "${_native_texture_dir}/*")
list(LENGTH _all_native_textures _native_texture_count)
if(NOT _native_texture_count EQUAL 139)
  message(FATAL_ERROR "Expected 139 centralized native texture assets, found ${_native_texture_count}")
endif()
if(DEFINED RAWIRON_BINARY_SHADER_DIR)
  foreach(_native_texture IN LISTS _all_native_textures)
    file(RELATIVE_PATH _native_relative "${_native_texture_dir}" "${_native_texture}")
    if(NOT EXISTS "${RAWIRON_BINARY_SHADER_DIR}/NativeTextures/${_native_relative}")
      message(FATAL_ERROR "Native texture was not recursively staged with SPIR-V: ${_native_relative}")
    endif()
  endforeach()
endif()
file(SHA256 "${_barbatos_texture}" _barbatos_lut_hash)
if(NOT _barbatos_lut_hash STREQUAL "d6e61b828662915dce504569714aff2e8fddeba65fe6268cb6f4a6b279cdc4cf")
  message(FATAL_ERROR "Native Barbatos LUT atlas migration changed source bytes unexpectedly")
endif()

set(_native_textures Layer.png AreaTex.png SearchTex.png lut.png)
foreach(_texture IN LISTS _native_textures)
  if(NOT EXISTS "${_native_texture_dir}/${_texture}")
    message(FATAL_ERROR "Migrated native post texture missing: ${_texture}")
  endif()
  if(EXISTS "${RAWIRON_WORKSPACE}/Source/RawIron.Render.Vulkan/ReferenceShaders/Textures/SweetFX/${_texture}"
      OR EXISTS "${RAWIRON_WORKSPACE}/Source/RawIron.Render.Vulkan/ReferenceShaders/Textures/${_texture}")
    message(FATAL_ERROR "Migrated post texture still exists in ReferenceShaders: ${_texture}")
  endif()
  if(DEFINED RAWIRON_BINARY_SHADER_DIR AND NOT EXISTS "${RAWIRON_BINARY_SHADER_DIR}/NativeTextures/${_texture}")
    message(FATAL_ERROR "Native post texture was not staged with SPIR-V: ${_texture}")
  endif()
endforeach()

file(SHA256 "${_native_texture_dir}/Layer.png" _layer_hash)
file(SHA256 "${_native_texture_dir}/AreaTex.png" _area_hash)
file(SHA256 "${_native_texture_dir}/SearchTex.png" _search_hash)
file(SHA256 "${_native_texture_dir}/lut.png" _lut_hash)
if(NOT _layer_hash STREQUAL "c9dc422c85df2c9c1ed04dbfc0421f0b4a41bf736adf50d009d172e49b3c05fc"
    OR NOT _area_hash STREQUAL "0044e6b420a8d98a9dc6a60bedbd43f75cd15ac6052fdedfb2f2f55d3077beed"
    OR NOT _search_hash STREQUAL "55a97853ab64174245701accf315ab63d41776c9cb2aa14c675e653684fd96f3"
    OR NOT _lut_hash STREQUAL "c81d61b0c7caa5cb8ff77b10183f2a00ffc5b4601ef328f7b9368e625fa9a214")
  message(FATAL_ERROR "Native post texture migration changed source bytes unexpectedly")
endif()

file(READ "${_native_asset}" _asset_text)
file(READ "${_full_shader}" _full_text)
file(READ "${_fast_shader}" _fast_text)
file(READ "${_notices}" _notice_text)
file(READ "${_runtime}" _runtime_text)
file(READ "${_pd80_native_asset}" _pd80_asset_text)
string(REGEX MATCHALL "resolveAuthoredTexturePath\\(textureRoot, relPath\\)" _texture_resolver_calls "${_runtime_text}")
list(LENGTH _texture_resolver_calls _texture_resolver_call_count)
if(_texture_resolver_call_count LESS 2)
  message(FATAL_ERROR "Vulkan material upload and warmup must share workspace-aware texture resolution")
endif()
foreach(_needle IN ITEMS "rawiron.post.crop_resize" "crop_resize" "CropResize/Resizer.fx")
  string(FIND "${_asset_text}${_full_text}${_fast_text}${_notice_text}" "${_needle}" _found)
  if(_found EQUAL -1)
    message(FATAL_ERROR "CropResize migration evidence missing: ${_needle}")
  endif()
endforeach()

foreach(_data_texture IN ITEMS sweetFxSmaaAreaTexturePath sweetFxSmaaSearchTexturePath reshadeLutTexturePath barbatosLutTexturePath)
  string(FIND "${_runtime_text}" "descriptorForAbsolutePath(${_data_texture}, false)" _data_format_found)
  if(_data_format_found EQUAL -1)
    message(FATAL_ERROR "Native data texture is not explicitly uploaded as UNORM: ${_data_texture}")
  endif()
endforeach()

foreach(_pd80_texture IN ITEMS pd80_bluenoise_rgba.png pd80_permtexture.png pd80_cinelut.png)
  string(FIND "${_runtime_text}" "nativePostTextureRoot / \"PD80\" / \"${_pd80_texture}\"" _pd80_path_found)
  if(_pd80_path_found EQUAL -1)
    message(FATAL_ERROR "PD80 native texture is not loaded by the Vulkan runtime: ${_pd80_texture}")
  endif()
  string(FIND "${_pd80_asset_text}" "native://PD80/${_pd80_texture}" _pd80_asset_path_found)
  if(_pd80_asset_path_found EQUAL -1)
    message(FATAL_ERROR "PD80 native texture is missing from the .rishader contract: ${_pd80_texture}")
  endif()
endforeach()
foreach(_needle IN ITEMS
    "descriptorForNativePostBundle(nativePostTexturePaths)"
    "layout(set = 7, binding = 0) uniform sampler2D nativePd80BlueNoiseTexture"
    "layout(set = 7, binding = 1) uniform sampler2D nativePd80PermTexture"
    "layout(set = 7, binding = 2) uniform sampler2D nativePd80CineLutTexture"
    "texture(nativePd80BlueNoiseTexture, noiseUv)"
    "texture(nativePd80PermTexture, hz)"
    "texture(nativePd80CineLutTexture, lutcoord.xy)")
  string(FIND "${_runtime_text}${_full_text}" "${_needle}" _pd80_wiring_found)
  if(_pd80_wiring_found EQUAL -1)
    message(FATAL_ERROR "PD80 native texture bundle is staged but not genuinely sampled: ${_needle}")
  endif()
endforeach()
foreach(_shader_text IN ITEMS _full_text _fast_text)
  string(FIND "${${_shader_text}}" "ApplyNativeCropScale" _function_found)
  string(FIND "${${_shader_text}}" "cropScaleFinalFilterStrength" _uniform_found)
  if(_function_found EQUAL -1 OR _uniform_found EQUAL -1)
    message(FATAL_ERROR "CropResize is not wired into both native composite paths")
  endif()
endforeach()

foreach(_function IN ITEMS ApplyRiAdaptiveDeband ApplyRiLocalSharpen ApplyRiInkOutline)
  foreach(_shader_text IN ITEMS _full_text _fast_text)
    string(FIND "${${_shader_text}}" "${_function}" _native_function_found)
    if(_native_function_found EQUAL -1)
      message(FATAL_ERROR "Raw Iron-owned post capability missing from a composite path: ${_function}")
    endif()
  endforeach()
endforeach()
foreach(_function IN ITEMS ApplyRiSignalGlitch ApplyRiNightVision)
  foreach(_shader_text IN ITEMS _full_text _fast_text)
    string(FIND "${${_shader_text}}" "${_function}" _native_function_found)
    if(_native_function_found EQUAL -1)
      message(FATAL_ERROR "Raw Iron signal/display capability missing from a composite path: ${_function}")
    endif()
  endforeach()
endforeach()
foreach(_pack IN ITEMS riSignalGlitchPack riNightVisionPack)
  string(FIND "${_runtime_text}" "cameraUniform.${_pack}" _runtime_pack_found)
  if(_runtime_pack_found EQUAL -1)
    message(FATAL_ERROR "Raw Iron signal/display uniform is not copied by the runtime: ${_pack}")
  endif()
endforeach()

foreach(_function IN ITEMS
    RiBlendLayer RiFontGlyphCoverage RiSafeReciprocal RiBoundedSceneColor
    ApplyRiHq4x ApplyRiHslShift ApplyRiLevelsPlus ApplyRiLightDof ApplyRiMagicBloom ApplyRiUiMask)
  foreach(_shader_text IN ITEMS _full_text _fast_text)
    string(FIND "${${_shader_text}}" "${_function}" _requested_function_found)
    if(_requested_function_found EQUAL -1)
      message(FATAL_ERROR "Requested native shader capability missing from a composite path: ${_function}")
    endif()
  endforeach()
endforeach()
foreach(_function IN ITEMS ApplyRiHq4x ApplyRiHslShift ApplyRiLevelsPlus ApplyRiLightDof ApplyRiMagicBloom ApplyRiUiMask)
  foreach(_shader_text IN ITEMS _full_text _fast_text)
    string(REGEX MATCHALL "${_function}\\(" _requested_function_occurrences "${${_shader_text}}")
    list(LENGTH _requested_function_occurrences _requested_function_count)
    if(_requested_function_count LESS 2)
      message(FATAL_ERROR "Requested native effect is declared but not invoked in a composite path: ${_function}")
    endif()
  endforeach()
endforeach()
foreach(_pack IN ITEMS
    riHq4xPack0 riHslAnchor0 riLevelsPlusPack0 riLightDofPack0 riMagicBloomPack0 riUiMaskPack0)
  string(FIND "${_runtime_text}" "cameraUniform.${_pack}" _requested_pack_found)
  if(_requested_pack_found EQUAL -1)
    message(FATAL_ERROR "Requested native shader uniform is not copied by the runtime: ${_pack}")
  endif()
endforeach()
foreach(_texture IN ITEMS MagicBloom_Dirt.png FontAtlas.png brussell/UIDetectMaskRGB.png)
  if(NOT EXISTS "${_native_texture_dir}/${_texture}")
    message(FATAL_ERROR "Requested native shader texture is missing: ${_texture}")
  endif()
endforeach()
foreach(_binding IN ITEMS
    "binding = 3) uniform sampler2D riMagicBloomDirtTexture"
    "binding = 4) uniform sampler2D riUiMaskTexture"
    "binding = 5) uniform sampler2D riFontAtlasTexture")
  foreach(_shader_text IN ITEMS _full_text _fast_text)
    string(FIND "${${_shader_text}}" "${_binding}" _requested_binding_found)
    if(_requested_binding_found EQUAL -1)
      message(FATAL_ERROR "Requested native texture binding is missing from a composite path: ${_binding}")
    endif()
  endforeach()
endforeach()
foreach(_sample IN ITEMS
    "texture(riMagicBloomDirtTexture"
    "texture(riUiMaskTexture"
    "texture(riFontAtlasTexture")
  foreach(_shader_text IN ITEMS _full_text _fast_text)
    string(FIND "${${_shader_text}}" "${_sample}" _requested_sample_found)
    if(_requested_sample_found EQUAL -1)
      message(FATAL_ERROR "Requested native texture is bound but never sampled: ${_sample}")
    endif()
  endforeach()
endforeach()
foreach(_path_needle IN ITEMS
    "nativePostTextureRoot / \"MagicBloom_Dirt.png\""
    "nativePostTextureRoot / \"brussell\" / \"UIDetectMaskRGB.png\""
    "nativePostTextureRoot / \"FontAtlas.png\"")
  string(FIND "${_runtime_text}" "${_path_needle}" _requested_path_found)
  if(_requested_path_found EQUAL -1)
    message(FATAL_ERROR "Requested native texture is not loaded by the Vulkan runtime: ${_path_needle}")
  endif()
endforeach()

file(READ "${_barbatos_asset}" _barbatos_asset_text)
foreach(_needle IN ITEMS "rawiron.post.barbatos_fake_hdr" "barbatos_fake_hdr" "Barbatos_LUT_Atlas.png")
  string(FIND "${_barbatos_asset_text}" "${_needle}" _found)
  if(_found EQUAL -1)
    message(FATAL_ERROR "Barbatos migration asset evidence missing: ${_needle}")
  endif()
endforeach()
foreach(_shader_text IN ITEMS _full_text _fast_text)
  string(FIND "${${_shader_text}}" "ApplyBarbatosFakeHdr" _function_found)
  string(FIND "${${_shader_text}}" "layout(set = 6, binding = 0) uniform sampler2D barbatosLutAtlas" _sampler_found)
  if(_function_found EQUAL -1 OR _sampler_found EQUAL -1)
    message(FATAL_ERROR "Barbatos uFakeHDR is not wired into both native composite paths")
  endif()
endforeach()

message(STATUS "Verified native CropResize and Barbatos uFakeHDR migrations and reference removal")
