# This test intentionally needs only the experience copy, never the upstream checkout.
file(REAL_PATH "${RAWIRON_SOURCE_DIR}" workspace)
set(asset_root "${workspace}/Games/CubeTest/assets/reference/threejs-r185")
file(READ "${asset_root}/asset-manifest.json" manifest)
string(JSON asset_count LENGTH "${manifest}" assets)
if(asset_count LESS 1)
  message(FATAL_ERROR "Cube Test reference manifest is empty")
endif()
math(EXPR last_asset "${asset_count} - 1")
foreach(index RANGE 0 ${last_asset})
  string(JSON relative GET "${manifest}" assets ${index} path)
  string(JSON expected_hash GET "${manifest}" assets ${index} sha256)
  string(JSON expected_bytes GET "${manifest}" assets ${index} bytes)
  if(IS_ABSOLUTE "${relative}" OR relative MATCHES "(^|/)\\.\\.(/|$)")
    message(FATAL_ERROR "Reference asset must stay inside the experience: ${relative}")
  endif()
  set(asset "${asset_root}/${relative}")
  file(REAL_PATH "${asset}" actual_path)
  if(NOT EXISTS "${asset}" OR IS_DIRECTORY "${asset}" OR NOT actual_path STREQUAL asset)
    message(FATAL_ERROR "Missing reference asset or external link: ${relative}")
  endif()
  file(SHA256 "${asset}" actual_hash)
  file(SIZE "${asset}" actual_bytes)
  if(NOT actual_hash STREQUAL expected_hash OR NOT actual_bytes EQUAL expected_bytes)
    message(FATAL_ERROR "Reference asset differs from the recorded upstream bytes: ${relative}")
  endif()
endforeach()
message(STATUS "Verified ${asset_count} project-owned Three.js reference files; no upstream checkout required")
