method=repeat
matchBlocks=copper_door exposed_copper_door weathered_copper_door oxidized_copper_door waxed_copper_door waxed_exposed_copper_door waxed_weathered_copper_door waxed_oxidized_copper_door
blockstates=half=lower
matchTiles=copper_door_bottom exposed_copper_door_bottom weathered_copper_door_bottom oxidized_copper_door_bottom waxed_copper_door_bottom waxed_exposed_copper_door_bottom waxed_weathered_copper_door_bottom waxed_oxidized_copper_door_bottom
width=1
height=1
tiles=1
