method=repeat
matchBlocks=acacia_door birch_door cherry_door bamboo_door mangrove_door oak_door spruce_door jungle_door dark_oak_door crimson_door warped_door pale_oak_door
blockstates=half=lower
matchTiles=acacia_door_bottom birch_door_bottom cherry_door_bottom bamboo_door_bottom mangrove_door_bottom oak_door_bottom spruce_door_bottom jungle_door_bottom dark_oak_door_bottom crimson_door_bottom warped_door_bottom pale_oak_door_bottom
width=1
height=1
tiles=1
