// Generated by Scripts/Generate-SerenityAdapter.py from Bliss composite12.fsh.
// Formula bodies, including the original sharpening weights, are preserved.
#version 450
#extension GL_GOOGLE_include_directive : require
layout(location = 0) in vec2 vUv;
layout(location = 0) out vec4 fragColor;
#include "SerenityColorCommon.glsl"
#include "SerenityTemporal.glsl"
#define texture2D texture
#define colortex7 hdrSceneLinear
#define texcoord vec2(vUv.x, 1.0-vUv.y)
#define texelSize serenity.controls[6].xy
#define MC_RENDER_QUALITY 1.0
#define UPSCALING_SHARPNENING 0.0
#define SHARPENING serenity.controls[1].w
#define SATURATION serenity.controls[0].y
#define CROSSTALK serenity.controls[0].z
#define UPPER_CURVE serenity.controls[1].x
#define LOWER_CURVE serenity.controls[1].y
#define saturate(x) clamp(x, 0.0, 1.0)
#define SHADOWS_TARGET SerenityGradeTarget(serenity.controls[2].rgb)
#define MIDS_TARGET SerenityGradeTarget(serenity.controls[3].rgb)
#define HIGHLIGHTS_TARGET SerenityGradeTarget(serenity.controls[4].rgb)
#define SHADOWS_GRADE_MUL serenity.controls[2].w
#define MIDS_GRADE_MUL serenity.controls[3].w
#define HIGHLIGHTS_GRADE_MUL serenity.controls[4].w
vec3 SerenityGradeTarget(vec3 rgb) { return length(rgb) < .001 ? vec3(0.0) : normalize(rgb); }
vec3 SerenityDisplayToLinear(vec3 c) {
    return mix(pow((c+.055)/1.055, vec3(2.4)), c/12.92, lessThanEqual(c, vec3(.04045)));
}
float lowerCurve(float x) {
	float y = 16 * x * (0.5 - x) * 0.1;
	return clamp(y, 0.0, 1.0);
}

float upperCurve(float x) {
	float y = 16 * (0.5 - x) * (x - 1.0) * 0.1;
	return clamp(y, 0.0, 1.0);
}

vec3 luminanceCurve(vec3 color){
	color.r += LOWER_CURVE * lowerCurve(color.r) + UPPER_CURVE * upperCurve(color.r);
	color.g += LOWER_CURVE * lowerCurve(color.g) + UPPER_CURVE * upperCurve(color.g);
	color.b += LOWER_CURVE * lowerCurve(color.b) + UPPER_CURVE * upperCurve(color.b);
	return color;
}

vec3 colorGrading(vec3 color) {
	float grade_luma = dot(color, vec3(1.0 / 3.0));
  float shadows_amount = saturate(-6.0 * grade_luma + 2.75);
	float mids_amount = saturate(-abs(6.0 * grade_luma - 3.0) + 1.25);
	float highlights_amount = saturate(6.0 * grade_luma - 3.25);

	vec3 graded_shadows = color * SHADOWS_TARGET * SHADOWS_GRADE_MUL * 1.7320508076;
	vec3 graded_mids = color * MIDS_TARGET * MIDS_GRADE_MUL * 1.7320508076;
	vec3 graded_highlights = color * HIGHLIGHTS_TARGET * HIGHLIGHTS_GRADE_MUL * 1.7320508076;

	return saturate(graded_shadows * shadows_amount + graded_mids * mids_amount + graded_highlights * highlights_amount);
}

vec3 contrastAdaptiveSharpening(vec3 color, vec2 sampleCoord){

  //Weights : 1 in the center, 0.5 middle, 0.25 corners
  vec3 albedoCurrent1 = texture2D(colortex7, sampleCoord + vec2(texelSize.x,texelSize.y)/MC_RENDER_QUALITY*0.5).rgb;
  vec3 albedoCurrent2 = texture2D(colortex7, sampleCoord + vec2(texelSize.x,-texelSize.y)/MC_RENDER_QUALITY*0.5).rgb;
  vec3 albedoCurrent3 = texture2D(colortex7, sampleCoord + vec2(-texelSize.x,-texelSize.y)/MC_RENDER_QUALITY*0.5).rgb;
  vec3 albedoCurrent4 = texture2D(colortex7, sampleCoord + vec2(-texelSize.x,texelSize.y)/MC_RENDER_QUALITY*0.5).rgb;
 
  vec3 m1 = -0.5/3.5*color + albedoCurrent1/3.5 + albedoCurrent2/3.5 + albedoCurrent3/3.5 + albedoCurrent4/3.5;
  
  vec3 std = abs(color - m1) + abs(albedoCurrent1 - m1) + abs(albedoCurrent2 - m1) +
  abs(albedoCurrent3 - m1) + abs(albedoCurrent3 - m1) + abs(albedoCurrent4 - m1);

  float contrast = 1.0 - luma(std)/5.0;

  color = color*(1.0+(SHARPENING+UPSCALING_SHARPNENING)*contrast) -
  (SHARPENING+UPSCALING_SHARPNENING)/(1.0-0.5/3.5)*contrast*(m1 - 0.5/3.5*color); 

  return color;
}

vec3 saturationAndCrosstalk(vec3 color){

	float luminance = luma(color);

	vec3 lumaColDiff = color - luminance;

	color = color + lumaColDiff*(-luminance*CROSSTALK + SATURATION);
  
  return color;
}

vec3 SerenityOutputAt(vec2 outputUv) {

  

	vec3 color = texture2D(colortex7,outputUv).rgb;

	if (serenity.controls[5].w > .5) {
    color = contrastAdaptiveSharpening(color, outputUv);
	}
  
  color = saturationAndCrosstalk(color);
  
  if (serenity.controls[5].y > .5) {
	  color = luminanceCurve(color);
  }

  if (serenity.controls[5].x > .5) {
	  color = colorGrading(color);
  }

	vec3 displayColor = clamp(SerenityDither(color, outputUv), 0.0, 1.0);
    return SerenityDisplayToLinear(SerenityFinite(displayColor));
}

void main() {
    vec2 uv = vec2(vUv.x, 1.0 - vUv.y);
    fragColor = vec4(SerenityTemporal(SerenityOutputAt(uv), uv), 1.0);
}
