name = "RawIron"
tagline = "a bare-metal game engine"
workspace_root = "N:\\RAWIRON"
documentation_dir = "Documentation"
source_dir = "Source"
apps_dir = "Apps"
tools_dir = "Tools"
config_dir = "Config"
assets_source_dir = "Assets/Source"
assets_cooked_dir = "Assets/Cooked"
projects_dir = "Projects"
sandbox_project_dir = "Projects/Sandbox"
sandbox_content_dir = "Projects/Sandbox/Content"
sandbox_scenes_dir = "Projects/Sandbox/Scenes"
sandbox_saved_dir = "Projects/Sandbox/Saved"
saved_dir = "Saved"
scripts_dir = "Scripts"
third_party_dir = "ThirdParty"
