method=repeat
matchBlocks=copper_door exposed_copper_door weathered_copper_door oxidized_copper_door waxed_copper_door waxed_exposed_copper_door waxed_weathered_copper_door waxed_oxidized_copper_door
blockstates=half=upper
matchTiles=copper_door_top exposed_copper_door_top weathered_copper_door_top oxidized_copper_door_top waxed_copper_door_top waxed_exposed_copper_door_top waxed_weathered_copper_door_top waxed_oxidized_copper_door_top
width=1
height=1
tiles=1
