method=repeat
matchBlocks=copper_bulb exposed_copper_bulb weathered_copper_bulb oxidized_copper_bulb waxed_copper_bulb waxed_exposed_copper_bulb waxed_weathered_copper_bulb waxed_oxidized_copper_bulb
blockstates=lit=true powered=true
matchTiles=copper_bulb_lit_powered exposed_copper_bulb_lit_powered weathered_copper_bulb_lit_powered oxidized_copper_bulb_lit_powered copper_bulb_lit_powered exposed_copper_bulb_lit_powered weathered_copper_bulb_lit_powered oxidized_copper_bulb_lit_powered
width=1
height=1
tiles=1
