method=repeat
matchBlocks=acacia_door birch_door cherry_door bamboo_door mangrove_door oak_door spruce_door jungle_door dark_oak_door crimson_door warped_door pale_oak_door
blockstates=half=upper
matchTiles=acacia_door_top birch_door_top cherry_door_top bamboo_door_top mangrove_door_top oak_door_top spruce_door_top jungle_door_top dark_oak_door_top crimson_door_top warped_door_top pale_oak_door_top
width=1
height=1
tiles=1
