method=repeat
matchBlocks=copper_bulb exposed_copper_bulb weathered_copper_bulb oxidized_copper_bulb waxed_copper_bulb waxed_exposed_copper_bulb waxed_weathered_copper_bulb waxed_oxidized_copper_bulb
blockstates=lit=true powered=false
matchTiles=copper_bulb_lit exposed_copper_bulb_lit weathered_copper_bulb_lit oxidized_copper_bulb_lit copper_bulb_lit exposed_copper_bulb_lit weathered_copper_bulb_lit oxidized_copper_bulb_lit
width=1
height=1
tiles=1
