"""Rebuild the native color adapter and catalog from the preserved Bliss source."""
from pathlib import Path
import hashlib
import json
import re
import sys

def emit(path, text):
    if "--check" in sys.argv:
        if not path.exists() or path.read_text(encoding="utf-8") != text:
            raise SystemExit(f"Generated Serenity file is stale: {path}")
    else:
        path.write_text(text, encoding="utf-8", newline="\n")

root = Path(__file__).resolve().parents[1]
reference = root / "ThirdParty/Bliss/2.1.2/shaders"
native = root / "Source/RawIron.Render.Vulkan/shaders"
output = native / "SerenityComposite.frag"
source = (reference / "dimensions/composite12.fsh").read_text(encoding="utf-8")
body = source[source.index("float lowerCurve(float x)"):]
body = body.replace("#ifdef CONTRAST_ADAPTATIVE_SHARPENING", "if (serenity.controls[5].w > .5) {")
body = body.replace("#ifdef LUMINANCE_CURVE", "if (serenity.controls[5].y > .5) {")
body = body.replace("#ifdef COLOR_GRADING_ENABLED", "if (serenity.controls[5].x > .5) {")
body = body.replace("#endif", "}")
body = body.replace("/* DRAWBUFFERS:7 */", "")
body = body.replace("gl_FragData[0].rgb = clamp(int8Dither(color, texcoord),0.0,1.0);",
                    "vec3 displayColor = clamp(SerenityDither(color, texcoord), 0.0, 1.0);\n"
                    "    return SerenityDisplayToLinear(SerenityFinite(displayColor));")
body = body.replace("void main()", "vec3 SerenityOutputAt(vec2 outputUv)")
main_start = body.index("vec3 SerenityOutputAt")
body = body[:main_start] + body[main_start:].replace("texcoord", "outputUv")
body += "\nvoid main() {\n    vec2 uv = vec2(vUv.x, 1.0 - vUv.y);\n    fragColor = vec4(SerenityTemporal(SerenityOutputAt(uv), uv), 1.0);\n}\n"
header = '''// Generated by Scripts/Generate-SerenityAdapter.py from Bliss composite12.fsh.
// Formula bodies, including the original sharpening weights, are preserved.
#version 450
#extension GL_GOOGLE_include_directive : require
layout(location = 0) in vec2 vUv;
layout(location = 0) out vec4 fragColor;
#include "SerenityColorCommon.glsl"
#include "SerenityTemporal.glsl"
#define texture2D texture
#define colortex7 hdrSceneLinear
#define texcoord vec2(vUv.x, 1.0-vUv.y)
#define texelSize serenity.controls[6].xy
#define MC_RENDER_QUALITY 1.0
#define UPSCALING_SHARPNENING 0.0
#define SHARPENING serenity.controls[1].w
#define SATURATION serenity.controls[0].y
#define CROSSTALK serenity.controls[0].z
#define UPPER_CURVE serenity.controls[1].x
#define LOWER_CURVE serenity.controls[1].y
#define saturate(x) clamp(x, 0.0, 1.0)
#define SHADOWS_TARGET SerenityGradeTarget(serenity.controls[2].rgb)
#define MIDS_TARGET SerenityGradeTarget(serenity.controls[3].rgb)
#define HIGHLIGHTS_TARGET SerenityGradeTarget(serenity.controls[4].rgb)
#define SHADOWS_GRADE_MUL serenity.controls[2].w
#define MIDS_GRADE_MUL serenity.controls[3].w
#define HIGHLIGHTS_GRADE_MUL serenity.controls[4].w
vec3 SerenityGradeTarget(vec3 rgb) { return length(rgb) < .001 ? vec3(0.0) : normalize(rgb); }
vec3 SerenityDisplayToLinear(vec3 c) {
    return mix(pow((c+.055)/1.055, vec3(2.4)), c/12.92, lessThanEqual(c, vec3(.04045)));
}
'''
# The source parameter called texcoord must not be expanded as the varying macro.
body = body.replace("vec3 contrastAdaptiveSharpening(vec3 color, vec2 texcoord)",
                    "vec3 contrastAdaptiveSharpening(vec3 color, vec2 sampleCoord)")
start = body.index("vec3 contrastAdaptiveSharpening")
end = body.index("vec3 saturationAndCrosstalk", start)
body = body[:start] + body[start:end].replace("texcoord", "sampleCoord") + body[end:]
emit(output, header + body)

native_notice = (
    "// Native engine copy of Bliss 2.1.2 shaders/lib/{name}.\n"
    "// Regenerated by Scripts/Generate-SerenityAdapter.py. Runtime compile must not include ThirdParty.\n"
)
for lib_name in ("color_transforms.glsl", "color_dither.glsl"):
    stem = "SerenityColorTransforms.glsl" if lib_name.startswith("color_t") else "SerenityColorDither.glsl"
    emit(
        native / stem,
        native_notice.format(name=lib_name) + (reference / "lib" / lib_name).read_text(encoding="utf-8"),
    )

files = []
for path in sorted(reference.rglob("*")):
    if path.is_file():
        blob = path.read_bytes()
        files.append(dict(path=path.relative_to(reference).as_posix(), bytes=len(blob), sha256=hashlib.sha256(blob).hexdigest()))

settings = []
for filename in ("lib/settings.glsl", "lib/climate_settings.glsl"):
    for line_number, line in enumerate((reference / filename).read_text(encoding="utf-8").splitlines(), 1):
        match = re.match(r"\s*(//\s*)?#define\s+(\w+)(.*)", line)
        if not match:
            continue
        value, _, comment = match[3].partition("//")
        settings.append(dict(name=match[2], enabled=not bool(match[1]), value=value.strip() or "true",
                             source=filename, line=line_number, description=comment.strip()))
manifest = dict(name="Serenity Processing Stack", source="Bliss 2.1.2 (Chocapic13 Shaders edit)",
    full_appearance_parity=False,
    native_color_stage=True,
    native_shader_root="Source/RawIron.Render.Vulkan/shaders",
    native_files=["SerenityColorCommon.glsl", "SerenityColorTransforms.glsl", "SerenityColorDither.glsl",
                  "SerenityRadiance.glsl", "SerenityTemporal.glsl", "SerenityCloudNoise.glsl",
                  "SerenityExposure.glsl", "SerenityExposure.frag", "SerenityToneMap.vert", "SerenityToneMap.frag", "SerenityComposite.frag"],
    compile_includes_third_party=False,
    files=files, settings=settings,
    native_stages=["color transforms (11 original tone mappers)", "saturation and crosstalk",
                   "contrast-adaptive sharpening", "luminance curves", "three-range color grading", "output dither",
                   "HDR bloom from the HDR mip chain",
                   "Bliss log-average auto-exposure (50 R2 taps on the 1/16 HDR mip)",
                   "Purkinje/rod mix",
                   "closest-velocity TAA (Bliss composite5 5-tap nearest depth + Catmull-Rom)",
                   "screen-space GI bounce (LPV stand-in)",
                   "water caustics, refraction, and absorption",
                   "volumetric sky clouds", "layered cloud shadows matching the sky march",
                   "screen-space sun shafts"],
    missing_renderer_inputs=["Bliss Minecraft atmospheric LUT and biome/weather state",
        "LPV voxel volumes",
        "Iris G-buffer material IDs and water volume lighting",
        "Iris entity/hand velocity attributes (camera closest-velocity from depth is native)",
        "pre-tonemap HDR temporal resolve with jitter and object motion vectors"])
emit(reference.parent / "port-manifest.json", json.dumps(manifest, indent=2)+"\n")
print(f"Generated Serenity composite; cataloged {len(files)} reference files and {len(settings)} definitions")
